(defpackage :system-lisp
  (:nicknames :sl)
  (:shadow :iter)
  (:shadow :bit)
  (:use :cl)
  (:use :iterate)
  (:use :cl-generator)

  (:export
   :sl-proc-status
   :sl-sim-status
   :sl-sim-process
   :sl-timing-control
   :sl-sim-event
   :sl-sync-event
   :sl-time-slot
   :sl-sim-event-region
   :sl-sim
   :to-int
   :to-uint
   :bit
   :bits
   :int
   :uint
   :uint-bit-get
   :uint-bit-set
   :int-bit-get
   :int-bit-set
   :uint-get-slice
   :uint-set-slice
   :int-get-slice
   :int-set-slice
   :sl-uint
   :sl-int
   :make-sl-int
   :make-sl-uint
   :sl-int-bits
   :sl-int-value
   :sl-uint-bits
   :sl-uint-value
   :spawn
   :sl-sim
   :sim-delay
   :sim-wait
   :sim-finish
   :emit-event
   :defun-res
   :defmethod-res
   :defres
   :lambda-res
   :c-for
   :forever
   :repeat
   :yield
   :fork-join
   :fork-join-any
   :fork-join-first
   :pcall
   :terminate-process
   :run
   :reset-sim
   :*sim*
   :*process-self*
   :time-now
   :sl-signal-object
   :sl-signal-binary
   :sl-signal-number
   :sl-signal-lambda
   :sl-signal-binary-lambda
   :sl-signal-bit-proxy
   :sl-signal-slice-proxy
   :sl-signal-concat-proxy
   :sl-message
   :sl-messagef
   :sl-debug
   :*sl-break-on-debug*
   :*sl-print-on-debug*
   :*sl-logger-verbosity*
   :->
   :break-loop
   :concat
   :connect-comb
   :connect-driver-load
   :connect-load-driver
   :create-component
   :elaborate
   :load-component
   :lsh
   :rsh
   :negedge
   :posedge
   :edge
   :setb
   :setnb
   :sl-lognot
   :sl-logxor
   :sl1+
   :sl1-
   :sl=
   :sl>
   :sl<
   :sl>=
   :sl<=
   :value
   :vcd-trace-component
   :sl-component
   :none
   :low
   :medium
   :high
   :full
   :build
   :connect
   :run
   :resume
   :return
   :pcallr
   :sl-port-base
   :sl-analysis-imp
   :sl-write-imp
   :sl-analysis-port
   :connect-port
   :sl-write
   :sl-analysis-export
   :sl-analysis-fifo
   :fifo-pop
   :fifo-push
   :fifo-clear
   :fifo-length
   :sl-write-imp-base
   :fifo-get
   :declare-sl-analysis-fifo
   :set-analysis-fifo-type
   :sl-fifo-ll
   :bit-one-count
   :one-count
   :relative-edge-wait
   :sim-db
   :vcd-db-handle-to-file
   :sl-dump-waves
   :continue-loop))

(setq *read-default-float-format* 'double-float)
