(in-package :system-lisp)

(defparameter *timeunit* -12)
(defparameter *timeprecision* -12) 

(declaim (inline unit-to-log10))
(defun unit-to-log10 (unit)
  (cond
    ((symbolp unit)
     (case unit
       (s 0)
       (ms -3)
       (us -6)
       (ns -9)
       (ps -12)
       (fs -15)))
    ((and (integerp unit) (member unit '(1 -3 -6 -9 -12 -15)))
     unit)
    (t (error "Invalid unit value: ~a" unit))))

(defmacro sl-tu (coeff unit)
  (assert (member coeff '(1 10 100)) (coeff) "Time unit coefficient can only be  1, 10 or 100. Provided value: ~a" coeff)
  (assert (member unit '(s ms us ns ps fs)) (unit) "Time unit can only be s, ms, us, ns, ps, fs. Provided value: ~a" unit)
  (let ((log10-coeff (floor (log coeff 10)))
	(log10-unit (unit-to-log10 unit)))
    (+ log10-coeff log10-unit)))

(defmacro sl-tp (coeff unit)
  (assert (member coeff '(1 10 100)) (coeff) "Time precision coefficient can only be  1, 10 or 100. Provided value: ~a" coeff)
  (assert (member unit '(s ms us ns ps fs)) (unit) "Time precision unit can only be s, ms, us, ns, ps, fs. Provided value: ~a" unit)
  (let ((log10-coeff (floor (log coeff 10)))
	(log10-unit (unit-to-log10 unit)))
    (+ log10-coeff log10-unit)))

(declaim (inline sl-time)
	 (ftype (function ((or double-float integer) symbol) (unsigned-byte 64))))
(defun sl-time (time unit)
  (multiple-value-bind (first) (round (* time (expt 10.0d0 (- (unit-to-log10 unit) *timeprecision*)))) first))

(defun get-timeprecision-string ()
  (case *timeprecision*
    (2 "100s")
    (1 "10s")
    (0 "1s")
    (-1 "100ms")
    (-2 "10ms")
    (-3 "1ms")
    (-4 "100us")
    (-5 "10us")
    (-6 "1us")
    (-7 "100ns")
    (-8 "10ns")
    (-9 "1ns")
    (-10 "100ps")
    (-11 "10ps")
    (-12 "1ps")
    (-13 "100fs")
    (-14 "10fs")
    (-15 "1fs")
    (otherwise (error "Invalid timeprecision value: ~a" *timeprecision*))))
